packageExtensions:
  "@react-spring/core@*":
    peerDependencies:
      react: ">=16.8.0"
  "@zeit/next-css@*":
    peerDependencies:
      webpack: ">=4.0.0"
  "@zeit/next-sass@*":
    peerDependencies:
      webpack: ">=4.0.0"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"

preferInteractive: true
