# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  pull_request:
    branches: [ develop, release ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v2
        
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
        
      - name: yarn install
        run: yarn install --frozen-lockfile --non-interactive 
      
      - name: Lint
        uses: samuelmeuli/lint-action@v1.5.3
        with:
          github_token: ${{ secrets.github_token }}
          eslint: true
          eslint_args: "--max-warnings 0"
          stylelint: true
          stylelint_args: "--max-warnings 0"
        
  build:
    runs-on: ubuntu-latest
    name: Build
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
    
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      
      - name: yarn install
        run: yarn install --frozen-lockfile --non-interactive 
    
      - run: yarn build
